### ISSUE TITLE
Chess variant

### ISSUE THREAD

**Issue by Fantactic** [gbtami/chessgroundx#1]
Hi, this isn't an issue but a request/question.  I've created a chess variant that I'd love to see available for live play through the site pychess-variants.herokuapp.com, especially as it has rules enforcement.  I'm seeking a programmer who would like to take on this challenge.  It involves a few pieces that move and interact in different ways, so it'd be a nice demonstration of your skills if it's accomplished.  It's still on an 8x8 board and has the same overall game objective.  Let me know what you think.  Please provide your e-mail address and we can take the conversation off GitHub for now if that's easier.

**Comment by gbtami** [comment]
pychess-variants has a Discord server. Join https://discord.gg/Z5p9TbM
