### ISSUE TITLE
Height and Width

### ISSUE THREAD

**Issue by rdeyo1129** [gbtami/chessgroundx#40]
Hello, I'm running into some issues and questions with board `dimensions`. I am using the component similar to as follows:
```
<Chessground
  (insert valid props here)
/>
```
For `fen`, I tried both a `8/8/8/8/8/8/8/8  w KQkq - 0 1` setup and a `2/2  w KQkq - 0 1` setup, is that picked up like that by the `fen` prop? This is how I'm using `dimensions` and is only displaying what seems to be the default 8x8 board. Any thoughts on this or restrictions I should be aware of that is causing this issue? Let me know if I can elaborate further. Thanks for your time.

![image](https://user-images.githubusercontent.com/18131850/198883031-610f8684-c4b3-4581-82d0-b67a4616f133.png)

**Comment by gbtami** [comment]
Possible your doubled(!) parenthesis causes the trouble.

**Comment by rdeyo1129** [comment]
Thanks for getting back to me, but that throws a lint error, I believe that is correct syntax because the first pair defines that you're going to pass an expression to the prop and the second pair is that you're passing in the object that seems to be defined in this documentation.

**Comment by gbtami** [comment]
Expected type of `dimensions` is definitely not an expression, but an object.

**Comment by rdeyo1129** [comment]
I was using that term semantically, you can pass any JS in between the outer braces.

**Comment by gbtami** [comment]
I don't know your code. This picture is not enough to guess what it is. Sry.
Anyhow, if you want to report a bug, provide a minimal working code to us  reproduce it please.

**Comment by rdeyo1129** [comment]
Ok I'll look into it a bit more and maybe get back to you. I think I am forgetting that I used something using it a little differently, I have it setup so that Chessground can be used as a React JSX component. That's where those double parentheses can usually be found if you want to pass an object like that. Thanks for the feedback.

**Comment by rdeyo1129** [comment]
If anyone stumbles upon this who was wondering and also using one of the `react-chessground` setups, my issue was that I didn't declare the prop type. Then you might want to look your styling by changing your piece and squares size percentages and the svg numbers.
